/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.CategoriasDAO;
import dao.FormasPagamentosDAO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.DespesasVO;
import servicos.DespesasServicos;

import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import modelo.CategoriasVO;
import modelo.FormasPagamentosVO;

/**
 *
 * @author 182310022
 */
public class GUIcadastroDespesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form Teste
     */
    public GUIcadastroDespesa() {
        initComponents();
        PreencherComboBoxFormaPagamento();
        PreencherComboBoxCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNomeDespesa = new javax.swing.JTextField();
        jtfValorDespesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbCategoriaDespesa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jcbFormaPagamentoDespesa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescricao = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtCadastrar = new javax.swing.JButton();
        jtfDataPagamentoDespesa = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de despesa");

        jtfNomeDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeDespesaActionPerformed(evt);
            }
        });

        jLabel1.setText("NOME");

        jLabel2.setText("VALOR");

        jLabel3.setText("DATA DE PAGAMENTO:");

        jcbCategoriaDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel4.setText("CATEGORIA");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcbFormaPagamentoDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel5.setText("FORMA DE PAGAMENTO");

        jButton2.setText("+");

        jtaDescricao.setColumns(20);
        jtaDescricao.setRows(5);
        jScrollPane1.setViewportView(jtaDescricao);

        jLabel7.setText("DESCRIÇÃO:");

        jLabel8.setText("DD/MM/AAAA");

        jbtCadastrar.setText("CADASTRAR");
        jbtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarActionPerformed(evt);
            }
        });

        try{
            jtfDataPagamentoDespesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));

        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na criação da máscara!");
        }
        jtfDataPagamentoDespesa.setToolTipText("");
        jtfDataPagamentoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataPagamentoDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbCategoriaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbFormaPagamentoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel1)
                                    .addGap(49, 49, 49)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfValorDespesa)
                            .addComponent(jtfNomeDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDataPagamentoDespesa)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jbtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfValorDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataPagamentoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbCategoriaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbFormaPagamentoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jbtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        private void cadastrar() {
        try {
            DespesasVO dVO = new DespesasVO();
            dVO.setNome(jtfNomeDespesa.getText());
            
            dVO.setValor(Double.parseDouble(jtfValorDespesa.getText()));
            dVO.setDescricao(jtaDescricao.getText());
            
            String dataCrua =  jtfDataPagamentoDespesa.getText();
            SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
            Date data = dataFormatada.parse(dataCrua);
            dVO.setDataPagamento(data);
            System.out.println(data);
            String categoriaSelect = jcbCategoriaDespesa.getSelectedItem().toString();
            CategoriasDAO cDAO = new CategoriasDAO();
            ArrayList<CategoriasVO> categoriasList  = cDAO.buscarCategoria();
            int categoriaID = getIdCategoria(categoriasList , categoriaSelect);
            System.out.println("");
            dVO.setCategoria(categoriaID);
            
            //cVO.setCategoria(categoriaSelect);
            String formapagamentoSelect = jcbFormaPagamentoDespesa.getSelectedItem().toString();
            //cVO.setFormaPagamento(formapagamentoSelect);
            FormasPagamentosDAO fpDAO = new FormasPagamentosDAO();
            ArrayList<FormasPagamentosVO> formasPagamentosList  = fpDAO.buscarFormaPagamento();
            
            int formaPagamentoID = getIdFormaPagamento(formasPagamentosList, formapagamentoSelect);
            dVO.setFormaPagamento(formaPagamentoID);

            

            
            
            
            /*
        Temos que enviar o objeto pVO para o banco.
        Assim a instrução sql da DAO ( ProdutoDAO) foi
        copiada na ProdutoServicos, que tem uma cópia dos métodos
             */
            DespesasServicos ds = servicos.ServicosFactory.getDespesasSevicos();

            //Chamando o método
            ds.cadastrarDespesas(dVO);

            //Retorno para o usuário
            JOptionPane.showMessageDialog(
                    null,
                    "Despesa Cadastrada com sucesso! ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro! GUICadastroDespesa " + e.getMessage());
        }//fecha o try catch

    }//fim do método cadastrar
         public int getIdCategoria(ArrayList<CategoriasVO> list , String nome){
        int numero = 1;
        for(CategoriasVO element : list ){
                    if(element.getNome().equals(nome)){
                        numero = element.getIdCategoria();
                    }
                }
        
    return numero; }
    
    public int getIdFormaPagamento(ArrayList<FormasPagamentosVO> list , String nome){
        int numero = 1;
        for(FormasPagamentosVO element : list ){
                    if(element.getNome().equals(nome)){
                        numero = element.getIdFormaPagamento();
                    }
                }
        
    return numero; }
    
        public void PreencherComboBoxFormaPagamento(){
        
        try {
            FormasPagamentosDAO fpDAO = new FormasPagamentosDAO();
            ResultSet rs = fpDAO.listarPerfil();
            
            while(rs.next()){
                Vector<Integer> codFormaPagamento = new Vector<Integer>();
                codFormaPagamento.addElement(rs.getInt(1));
                jcbFormaPagamentoDespesa.addItem(rs.getString(2));                
            }//fim do while
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro GUICadastroDespesa.PreencherComboBoxFormaPagamento " + e.getMessage());
        }//fim do try catch
        
    }//fim do método restaurarPerfilComboBox
    
    public void PreencherComboBoxCategoria(){
        
        try {
            CategoriasDAO cDAO = new CategoriasDAO();
            ResultSet rs = cDAO.listarPerfil();
            
            while(rs.next()){
                Vector<Integer> codCategoria = new Vector<Integer>();
                codCategoria.addElement(rs.getInt(1));
                jcbCategoriaDespesa.addItem(rs.getString(2));                
            }//fim do while
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro GUICadastroDespesa.PreencherComboBoxCategoria " + e.getMessage());
        }//fim do try catch
        
    }//fim do método restaurarPerfilComboBox
    private void jtfNomeDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeDespesaActionPerformed

    private void jbtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarActionPerformed
cadastrar();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         GUIcadastroCategoria ccat = new GUIcadastroCategoria();
            this.add(ccat);
                ccat.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfDataPagamentoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataPagamentoDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataPagamentoDespesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtCadastrar;
    private javax.swing.JComboBox<String> jcbCategoriaDespesa;
    private javax.swing.JComboBox<String> jcbFormaPagamentoDespesa;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JFormattedTextField jtfDataPagamentoDespesa;
    private javax.swing.JTextField jtfNomeDespesa;
    private javax.swing.JTextField jtfValorDespesa;
    // End of variables declaration//GEN-END:variables
}
