/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import modelo.FormasPagamentosVO;
import servicos.FormasPagamentosServicos;
/**
 *
 * @author 182310022
 */
public class GUIcadastroFormaPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIcadastroCategoria
     */
    public GUIcadastroFormaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNomeFormaPagamento = new javax.swing.JTextField();
        jbtCadastrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("NOME:");

        jbtCadastrar.setText("CADASTRAR");
        jbtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNomeFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jbtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomeFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jbtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarActionPerformed
        cadastrar();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCadastrarActionPerformed
    private void cadastrar() {
        try {
            FormasPagamentosVO fVO = new FormasPagamentosVO();
            fVO.setNome(jtfNomeFormaPagamento.getText());

            

            

            

            
            
            
            /*
        Temos que enviar o objeto pVO para o banco.
        Assim a instrução sql da DAO ( ProdutoDAO) foi
        copiada na ProdutoServicos, que tem uma cópia dos métodos
             */
            FormasPagamentosServicos fps = servicos.ServicosFactory.getFormasPagamentosServicos();

            //Chamando o método
            fps.cadastrarFormaPagamento(fVO);

            //Retorno para o usuário
            JOptionPane.showMessageDialog(
                    null,
                    "Forma de Pagamento Cadastrado com sucesso! ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro! GUICadastroFormaPagamento " + e.getMessage());
        }//fecha o try catch

    }//fim do método cadastrar

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtCadastrar;
    private javax.swing.JTextField jtfNomeFormaPagamento;
    // End of variables declaration//GEN-END:variables
}
