/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import com.sun.glass.events.KeyEvent;
import dao.CategoriasDAO;
import dao.DespesasDAO;
import dao.FormasPagamentosDAO;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.*;
import modelo.CategoriasVO;
import modelo.DespesasVO;
import modelo.FormasPagamentosVO;
import servicos.DespesasServicos;
import servicos.ServicosFactory;
import servicos.FormasPagamentosServicos;
import servicos.CategoriasServicos;
import utilidades.Conversao;
/**
 *
 * @author cralves
 */
public class GUIManutencaoDespesas extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
                new Object[][]{},
            new Object[]{"Código", "Nome", "Valor", "Descricao", "Data de pagamento", "Categoria", "Forma de pagamento"}
    );
    /**
     * Creates new form GUIManutencaoProdutos
     */
    public GUIManutencaoDespesas() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfCodigo = new javax.swing.JTextField();
        jbtnConfirmarAlteracao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbCategoriaDespesa = new javax.swing.JComboBox<>();
        jcbFormaPagamentoDespesa = new javax.swing.JComboBox<>();
        jtfDataPagamento = new javax.swing.JFormattedTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbtnPreencher = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jbtnDeletar = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProduto = new javax.swing.JTable();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jtfPesquisaPro = new javax.swing.JTextField();
        jcbPesquisaPro = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção Despesa");

        jLabel1.setText("Descricao");

        jLabel2.setText("Valor ");

        jLabel3.setText("Nome");

        jLabel4.setText("Código");

        jtfCodigo.setEditable(false);
        jtfCodigo.setFocusable(false);

        jbtnConfirmarAlteracao.setText("Confirmar Alteração");
        jbtnConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarAlteracaoActionPerformed(evt);
            }
        });
        jbtnConfirmarAlteracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnConfirmarAlteracaoKeyPressed(evt);
            }
        });

        jLabel6.setText("Data de pagamento");

        jLabel7.setText("Categoria");

        jLabel8.setText("Forma de pagamento");

        jcbCategoriaDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jcbFormaPagamentoDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        try{
            jtfDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));

        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na criação da máscara!");
        }
        jtfDataPagamento.setToolTipText("");
        jtfDataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataPagamentoActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfDescricao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnConfirmarAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcbCategoriaDespesa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcbFormaPagamentoDespesa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfDataPagamento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jbtnConfirmarAlteracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jcbCategoriaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jcbFormaPagamentoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jcbCategoriaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFormaPagamentoDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnConfirmarAlteracao)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jbtnPreencher.setText("Preencher");
        jbtnPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreencherActionPerformed(evt);
            }
        });

        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });

        jbtnAlterar.setText("Alterar");
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });
        jbtnAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnAlterarKeyPressed(evt);
            }
        });

        jbtnDeletar.setText("Deletar");
        jbtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeletarActionPerformed(evt);
            }
        });
        jbtnDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnDeletarKeyPressed(evt);
            }
        });

        jLayeredPane2.setLayer(jbtnPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnPreencher)
                .addGap(40, 40, 40)
                .addComponent(jbtnLimpar)
                .addGap(39, 39, 39)
                .addComponent(jbtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnDeletar)
                .addGap(27, 27, 27))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPreencher)
                    .addComponent(jbtnLimpar)
                    .addComponent(jbtnAlterar)
                    .addComponent(jbtnDeletar))
                .addContainerGap())
        );

        jtProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Valor", "Descricao", "Data de Pagamento", "Categoria", "Forma de pagamento"
            }
        ));
        jtProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProduto);

        jLayeredPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabel5.setText("Pesquisa");

        jtfPesquisaPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisaProKeyReleased(evt);
            }
        });

        jcbPesquisaPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Valor", "Data de Pagamento", "Categoria", "Forma de pagamento" }));
        jcbPesquisaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPesquisaProActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtfPesquisaPro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jcbPesquisaPro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtfPesquisaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jcbPesquisaPro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPesquisaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPesquisaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane4)
                    .addComponent(jLayeredPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLayeredPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     //Métodos Criados Manualmente
    private void preencherTabela(){
        try {
            //Buscando objeto na ProdutoServicos
            DespesasServicos ps = ServicosFactory.getDespesasSevicos();
            FormasPagamentosDAO fpDAO = new FormasPagamentosDAO();
            CategoriasDAO cDAO = new CategoriasDAO();
            
            
           // ResultSet rs1 = fpDAO.listarPerfil();
          //  ResultSet rs2 = cDAO.listarPerfil();
            
            //Criando um ArrayList<ProdutoVO> vazio para receber o ArryaList com os dados
            ArrayList<CategoriasVO> categorias = new ArrayList<>();
            ArrayList<FormasPagamentosVO> formaspagamentos = new ArrayList<>();
            ArrayList<DespesasVO> despesa = new ArrayList<>();
            
            //Recebendo o ArrayList cheio no Produto
            despesa = ps.buscarDespesa();
            categorias = cDAO.buscarCategoria();
            formaspagamentos = fpDAO.buscarFormaPagamento();
           // DespesasDAO DDAO = new DespesasDAO();
             //despesa = DDAO.buscarDespesa();

            //System.out.println(categorias.get(2).getNome());
            for ( int i = 0; i < despesa.size(); i++) {
                String categoriaTEMP = "";
                String formapagamentoTEMP = "";
                //Date datapagamento = Conversao.dataConverterToDB(despesa.get(i).getDataPagamento());
                
                for (CategoriasVO categoria : categorias){
                 if(categoria.getIdCategoria() == despesa.get(i).getCategoria()){
                     categoriaTEMP = categoria.getNome();
                     System.out.println(categoriaTEMP);
                 }
             }
                for (FormasPagamentosVO formapagamento : formaspagamentos){
                 if(formapagamento.getIdFormaPagamento()== despesa.get(i).getFormaPagamento()){
                     formapagamentoTEMP = formapagamento.getNome();
                     System.out.println(formapagamentoTEMP);
                 }
             }
                String datacagada = Conversao.dataFormaterToDB(despesa.get(i).getDataPagamento());
                System.out.println(datacagada);
                dtm.addRow(new String[] { 
                    String.valueOf(despesa.get(i).getIdDespesa()),
                    String.valueOf(despesa.get(i).getNome() ),
                    String.valueOf(despesa.get(i).getValor() ),
                    String.valueOf(despesa.get(i).getDescricao() ),
                    //String.valueOf(despesa.get(i).getDataPagamento()),
                    datacagada,
                    
                    //categorias.get(despesa.get(i).getCategoria()).getNome(),
                    categoriaTEMP,
                   // String.valueOf(despesa.get(i).getCategoria() ),
                    formapagamentoTEMP,
                    //String.valueOf(despesa.get(i).getFormaPagamento()),
                }
                
                );
                //System.out.println(categorias.get(despesa.get(i).getCategoria()).getNome());
            }//fecha o laço for
            
            //Adicionando modelode tabela com os dados na tabela Produto
            jtProduto.setModel(dtm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro! GUIManutencaoDespesas.preencherTabela" + e.getMessage()  );
        }//fim do catch
    }//fim do método preencherTabela
    
    private void limparTabela(){
        dtm.setNumRows(0);
    }//fim do método limparTabela
    
    private void filtrar(){
        try {
            if( jtfPesquisaPro.getText().isEmpty() ) {
                preencherTabela();
            }else{
                //ProdutoServicos ps = ServicosFactory.getProdutoServicos();
                DespesasServicos ps = ServicosFactory.getDespesasSevicos();
                String pesquisa = (String) jcbPesquisaPro.getSelectedItem();
                String query;
                if( pesquisa.equals("Código")){
                    query = "where idDespesa =  " + jtfPesquisaPro.getText();
                }else if( pesquisa.equals("Nome")){
                    query = "where nome like '%" + jtfPesquisaPro.getText() + "%' ";
                }else if( pesquisa.equals("Valor")) {
                    query = "where valor = " + jtfPesquisaPro.getText();
                }else{
                    query = "where quantidade = " + jtfPesquisaPro.getText();
                }//fim do else
                 
                //Criando Array vazio para receber os dados do ArrayList
                ArrayList<DespesasVO> despesa = new ArrayList<>();
                
                //Recebendo o ArrayList cheio no produto
                despesa = ps.filtrarDespesa(query);
                
                for( int i = 0; i < despesa.size(); i++){
                    dtm.addRow(new String[] {
                        String.valueOf(despesa.get(i).getIdDespesa()),
                        String.valueOf(despesa.get(i).getNome()),
                        String.valueOf(despesa.get(i).getValor()),
                        String.valueOf(despesa.get(i).getDescricao()),
                        String.valueOf(despesa.get(i).getDataPagamento()),
                        String.valueOf(despesa.get(i).getCategoria()),
                        String.valueOf(despesa.get(i).getFormaPagamento()),
                    });
                }//fecha o laço for
                
                //Adicionando o modelo de tablea com os dados na tabela jtProduto
                jtProduto.setModel(dtm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro ao filtrar produto! GUIManutencaoProduto.filtrar " + e.getMessage() );
        }
    }//fecha o método filtrar
    
    private void deletarDespesa(){
        try {
            int linha = jtProduto.getSelectedRow();
            
            if( linha == -1 ){
                JOptionPane.showMessageDialog(
                        null,
                        "Por favor selecione uma linha!");
            }else{
                //ProdutoServicos ps = ServicosFactory.getProdutoServicos();
                DespesasServicos ps = ServicosFactory.getDespesasSevicos();
                String codDespesa = (String) jtProduto.getValueAt(linha, 0);
                ps.deletarDespesa(Integer.parseInt(codDespesa));
                
                //Mensagem para o usuário
                              
                JOptionPane.showMessageDialog(
                        null,
                        "Despesa excluída com sucesso!");
            }//fim do else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro ao deletar despesa! GUIManutencaoDespesa.deletar" + e.getMessage() );
        }
    }//fim do método deletarProduto
    
    
    private void alterarDespesa(){
        int linha = jtProduto.getSelectedRow();
        if(linha != -1){
            PreencherComboBoxFormaPagamento();
            PreencherComboBoxCategoria();
            jtfCodigo.setText((String) jtProduto.getValueAt(linha, 0));
            jtfNome.setText((String) jtProduto.getValueAt(linha, 1));
            jtfValor.setText((String) jtProduto.getValueAt(linha, 2));
            jtfDescricao.setText((String) jtProduto.getValueAt(linha, 3));
            jtfDataPagamento.setText((String) jtProduto.getValueAt(linha, 4));

            jcbCategoriaDespesa.setSelectedItem((String) jtProduto.getValueAt(linha, 5));
            jcbFormaPagamentoDespesa.setSelectedItem((String) jtProduto.getValueAt(linha, 6));

        }else{
            JOptionPane.showMessageDialog(
                    null,
                    "Você não selecionou nenhuma linha!");
        }//fecha o if else
    }//fim do método alterarProduto
    
    
    public void confirmarAlteracao(){
        try {
            DespesasVO dVO = new DespesasVO();
            if(jtfNome.getText().isEmpty() ||
                    jtfValor.getText().isEmpty() ||
                    jtfDataPagamento.getText().isEmpty() ) 
            {
                JOptionPane.showMessageDialog(
                        null,
                        "Erro! Por favor insira as informações corretamente!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }else{
                dVO.setIdDespesa(Integer.parseInt(jtfCodigo.getText() ) );
                dVO.setNome(jtfNome.getText() );
                dVO.setValor(Double.parseDouble(jtfValor.getText() ) );
                dVO.setDescricao(jtfDescricao.getText()  );
                
                String dataCrua =  jtfDataPagamento.getText();
                
            SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
            Date data = dataFormatada.parse(dataCrua);
                System.out.println(data);
            dVO.setDataPagamento(data);
            
            String categoriaSelect = jcbCategoriaDespesa.getSelectedItem().toString();
            CategoriasDAO cDAO = new CategoriasDAO();
            ArrayList<CategoriasVO> categoriasList  = cDAO.buscarCategoria();
            int categoriaID = getIdCategoria(categoriasList , categoriaSelect);
            System.out.println("");
            dVO.setCategoria(categoriaID);
            
            //cVO.setCategoria(categoriaSelect);
            String formapagamentoSelect = jcbFormaPagamentoDespesa.getSelectedItem().toString();
            //cVO.setFormaPagamento(formapagamentoSelect);
            FormasPagamentosDAO fpDAO = new FormasPagamentosDAO();
            ArrayList<FormasPagamentosVO> formasPagamentosList  = fpDAO.buscarFormaPagamento();
            
            int formaPagamentoID = getIdFormaPagamento(formasPagamentosList, formapagamentoSelect);
            dVO.setFormaPagamento(formaPagamentoID);
                
                DespesasServicos ps = ServicosFactory.getDespesasSevicos();
                ps.alterarDespesa(dVO);
                
                JOptionPane.showMessageDialog(
                        null,
                        "Despesa alterada com sucesso!");
            }//fim do if else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro!" + e.getMessage());
        }
    }//fim do método confirmarAlteracao
    public int getIdCategoria(ArrayList<CategoriasVO> list , String nome){
        int numero = 1;
        for(CategoriasVO element : list ){
                    if(element.getNome().equals(nome)){
                        numero = element.getIdCategoria();
                    }
                }
        
    return numero; }
    
    public int getIdFormaPagamento(ArrayList<FormasPagamentosVO> list , String nome){
        int numero = 1;
        for(FormasPagamentosVO element : list ){
                    if(element.getNome().equals(nome)){
                        numero = element.getIdFormaPagamento();
                    }
                }
        
    return numero; }
    public void PreencherComboBoxFormaPagamento(){
        
        try {
            FormasPagamentosDAO fpDAO = new FormasPagamentosDAO();
            ResultSet rs = fpDAO.listarPerfil();
            
            while(rs.next()){
                Vector<Integer> codFormaPagamento = new Vector<Integer>();
                codFormaPagamento.addElement(rs.getInt(1));
                jcbFormaPagamentoDespesa.addItem(rs.getString(2));                
            }//fim do while
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro GuiLogin.restaurarPerfilComboBox " + e.getMessage());
        }//fim do try catch
        
    }//fim do método restaurarPerfilComboBox
    
    public void PreencherComboBoxCategoria(){
        
        try {
            CategoriasDAO cDAO = new CategoriasDAO();
            ResultSet rs = cDAO.listarPerfil();
            
            while(rs.next()){
                Vector<Integer> codCategoria = new Vector<Integer>();
                codCategoria.addElement(rs.getInt(1));
                jcbCategoriaDespesa.addItem(rs.getString(2));                
            }//fim do while
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Erro GuiLogin.restaurarPerfilComboBox " + e.getMessage());
        }//fim do try catch
        
    }//fim do método restaurarPerfilComboBox
     MaskFormatter jftfData;

    public Date formatarDatas(){
        try{
        jftfData = new MaskFormatter("##/##/####");
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na criação da máscara!");
        }
        return null;
    }//fim do método formatarData
    
    
    //Eventos Gerados
    
    private void jbtnPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreencherActionPerformed
       limparTabela();
       preencherTabela();
       PreencherComboBoxFormaPagamento();
       PreencherComboBoxCategoria();
       
    }//GEN-LAST:event_jbtnPreencherActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jtfPesquisaProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisaProKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtfPesquisaProKeyReleased

    private void jbtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeletarActionPerformed
        deletarDespesa();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnDeletarActionPerformed

    private void jbtnDeletarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnDeletarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            deletarDespesa();
            limparTabela();
            preencherTabela();
        }
    }//GEN-LAST:event_jbtnDeletarKeyPressed

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed
       alterarDespesa();
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    private void jbtnAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnAlterarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            alterarDespesa();
        }
    }//GEN-LAST:event_jbtnAlterarKeyPressed

    private void jbtnConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarAlteracaoActionPerformed
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbtnConfirmarAlteracaoActionPerformed

    private void jbtnConfirmarAlteracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnConfirmarAlteracaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            confirmarAlteracao();
            limparTabela();
            preencherTabela();
        }
    }//GEN-LAST:event_jbtnConfirmarAlteracaoKeyPressed

    private void jcbPesquisaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPesquisaProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPesquisaProActionPerformed

    private void jtfDataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataPagamentoActionPerformed

    private void jtProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutoMouseClicked
        System.out.println(jtProduto.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_jtProdutoMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnConfirmarAlteracao;
    private javax.swing.JButton jbtnDeletar;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnPreencher;
    private javax.swing.JComboBox<String> jcbCategoriaDespesa;
    private javax.swing.JComboBox<String> jcbFormaPagamentoDespesa;
    private javax.swing.JComboBox<String> jcbPesquisaPro;
    private javax.swing.JTable jtProduto;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JFormattedTextField jtfDataPagamento;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPesquisaPro;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
