/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
/**
 *
 * @author 182310022
 */
public class GUItelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form GUIlogin
     */
    public GUItelaInicial() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiConta = new javax.swing.JMenuItem();
        jmiEditarConta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiCadastroDespesa = new javax.swing.JMenuItem();
        jmiEdicaoDespesa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiCadastroCategoria = new javax.swing.JMenuItem();
        jmiEdicaoCategoria = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiCadastroFormaPagamento = new javax.swing.JMenuItem();
        jmiEdicaoFormaPagamento = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jButton1.setText("jButton1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        jMenu1.setText("Contas");

        jmiConta.setText("Criar Conta");
        jmiConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiConta);

        jmiEditarConta.setText("Editar/Excluir");
        jmiEditarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarContaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiEditarConta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Despesas");

        jmiCadastroDespesa.setText("Criar Despesa");
        jmiCadastroDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroDespesaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCadastroDespesa);

        jmiEdicaoDespesa.setText("Editar/Excluir");
        jmiEdicaoDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEdicaoDespesaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiEdicaoDespesa);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Categorias");

        jmiCadastroCategoria.setText("Criar Categoria");
        jmiCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiCadastroCategoria);

        jmiEdicaoCategoria.setText("Editar/Excluir");
        jmiEdicaoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEdicaoCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiEdicaoCategoria);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Formas de pagamento");

        jmiCadastroFormaPagamento.setText("Salvar Forma de pagamento");
        jmiCadastroFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroFormaPagamentoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiCadastroFormaPagamento);

        jmiEdicaoFormaPagamento.setText("Editar/Excluir");
        jmiEdicaoFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEdicaoFormaPagamentoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiEdicaoFormaPagamento);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Relatórios");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("TESTE");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContaActionPerformed
    GUIcadastroContas cc = new GUIcadastroContas();
        jdpAreaDeTrabalho.add(cc);
    cc.setVisible(true);             // TODO add your handling code here:

    }//GEN-LAST:event_jmiContaActionPerformed

    private void jmiEditarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarContaActionPerformed
         GUIManutencaoContas mc = new GUIManutencaoContas();
            jdpAreaDeTrabalho.add(mc);
                mc.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jmiEditarContaActionPerformed

    private void jmiCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroCategoriaActionPerformed
        GUIcadastroCategoria ccat = new GUIcadastroCategoria();
            jdpAreaDeTrabalho.add(ccat);
                ccat.setVisible(true);  
        // TODO add your handling code here         // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCadastroCategoriaActionPerformed

    private void jmiCadastroDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroDespesaActionPerformed
        GUIcadastroDespesa cd = new GUIcadastroDespesa();
        jdpAreaDeTrabalho.add(cd);
        cd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCadastroDespesaActionPerformed

    private void jmiEdicaoDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEdicaoDespesaActionPerformed
     GUIManutencaoDespesas cmd = new GUIManutencaoDespesas();
        jdpAreaDeTrabalho.add(cmd);
        cmd.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jmiEdicaoDespesaActionPerformed

    private void jmiCadastroFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroFormaPagamentoActionPerformed
    GUIcadastroFormaPagamento fp = new GUIcadastroFormaPagamento();
            jdpAreaDeTrabalho.add(fp);
                fp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCadastroFormaPagamentoActionPerformed

    private void jmiEdicaoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEdicaoCategoriaActionPerformed
     GUIManutencaoCategorias cmc = new GUIManutencaoCategorias();
        jdpAreaDeTrabalho.add(cmc);
        cmc.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiEdicaoCategoriaActionPerformed

    private void jmiEdicaoFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEdicaoFormaPagamentoActionPerformed
     GUIManutencaoFormasPagamentos mfp = new GUIManutencaoFormasPagamentos();
        jdpAreaDeTrabalho.add(mfp);
        mfp.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jmiEdicaoFormaPagamentoActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
          GUIRelatorios cr = new GUIRelatorios();
        jdpAreaDeTrabalho.add(cr);
        cr.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUItelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUItelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUItelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUItelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUItelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JMenuItem jmiCadastroCategoria;
    private javax.swing.JMenuItem jmiCadastroDespesa;
    private javax.swing.JMenuItem jmiCadastroFormaPagamento;
    private javax.swing.JMenuItem jmiConta;
    private javax.swing.JMenuItem jmiEdicaoCategoria;
    private javax.swing.JMenuItem jmiEdicaoDespesa;
    private javax.swing.JMenuItem jmiEdicaoFormaPagamento;
    private javax.swing.JMenuItem jmiEditarConta;
    // End of variables declaration//GEN-END:variables
}
